### ISSUE TITLE
Figure out sms "view"

### ISSUE THREAD

**Issue by pierrebeugnot** [PeaceGeeksSociety/amani-sms#4]
@suyonsohn just a quick question. I know it's been a while :) but do you remember if we had to create a view, a type or anything else after activating the module?

**Comment by suyonsohn** [comment]
Sorry for the late reply. Yes, you do need a view type file or tpl or hook
or preprocessor etc. Have you figured it out?

**Comment by pierrebeugnot** [comment]
@suyonsohn so we do have a hook here https://github.com/PeaceGeeksSociety/amani-sms/blob/dev/amani/modules/custom/amani_sms/amani_sms.module#L4

Is that what you're talking about? 

I'm wondering where to find the actual view of the messages with the map :)
